import '../../domain/entities/export_assignee.dart';
import '../../domain/entities/export_request.dart';
import '../../domain/entities/export_result.dart';
import '../../domain/repositories/export_repository.dart';
import '../datasources/export_file_data_source.dart';
import '../datasources/export_remote_data_source.dart';
import '../models/export_dataset.dart';

class ExportRepositoryImpl implements ExportRepository {
  const ExportRepositoryImpl({
    required ExportRemoteDataSource remoteDataSource,
    required ExportFileDataSource fileDataSource,
  })  : _remoteDataSource = remoteDataSource,
        _fileDataSource = fileDataSource;

  final ExportRemoteDataSource _remoteDataSource;
  final ExportFileDataSource _fileDataSource;

  @override
  Future<ExportResult> generateExport(ExportRequest request) async {
    final modules = request.effectiveModules;
    final dataset = modules.length <= 1
        ? await _remoteDataSource.buildDataset(request)
        : await _buildCombinedDataset(request, modules);
    final result = _fileDataSource.generateFile(
      request: request,
      dataset: dataset,
    );
    await _remoteDataSource.logExportGenerated(
      request: request,
      dataset: dataset,
    );
    return result;
  }

  Future<ExportDataset> _buildCombinedDataset(
    ExportRequest request,
    List<ExportModule> modules,
  ) async {
    final sheets = <ExportSheet>[];
    final summary = <String, String>{};
    var totalRows = 0;
    var limited = false;

    for (final module in modules) {
      final moduleRequest = request.copyWith(
        module: module,
        columns: const <String>[],
      );
      final dataset = await _remoteDataSource.buildDataset(moduleRequest);
      totalRows += dataset.recordCount;
      limited = limited || dataset.limitedByCap;
      final moduleLabel = moduleRequest.labels['module.${module.name}'] ?? module.name;
      summary[moduleLabel] = dataset.recordCount.toString();
      sheets.add(
        ExportSheet(
          name: moduleLabel,
          columns: dataset.columns,
          rows: dataset.rows,
        ),
      );
      sheets.addAll(dataset.extraSheets);
    }

    return ExportDataset(
      columns: const [],
      rows: const [],
      summary: {
        request.labels['product'] ?? 'Product': 'Masar CRM',
        request.labels['company'] ?? 'Company': request.actor.companyName,
        request.labels['reportName'] ?? 'Report':
            request.labels['multipleReports'] ?? 'Multiple reports',
        request.labels['generatedBy'] ?? 'Generated by': request.actor.name,
        request.labels['recordCount'] ?? 'Records': totalRows.toString(),
        ...summary,
      },
      extraSheets: sheets,
      limitedByCap: limited,
      recordCountOverride: totalRows,
    );
  }

  @override
  Future<List<ExportAssignee>> getEligibleAssignees(ExportActor actor) {
    return _remoteDataSource.getEligibleAssignees(actor);
  }
}
