// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCteQzvKC5G4z4J-X8jivrtbYX4GObFOGU',
    appId: '1:138177769693:web:7c3cc46c0cd53057ae6b34',
    messagingSenderId: '138177769693',
    projectId: 'real-escrm-ia',
    authDomain: 'real-escrm-ia.firebaseapp.com',
    storageBucket: 'real-escrm-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY2cVTZyLnOSgUTAC9FlHLpjmpIdSZLdQ',
    appId: '1:138177769693:android:8b06080ca847d808ae6b34',
    messagingSenderId: '138177769693',
    projectId: 'real-escrm-ia',
    storageBucket: 'real-escrm-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwElfnXfu6SgzlTKuqNKuQ47ahyX3hlWk',
    appId: '1:138177769693:ios:27c83f311354560bae6b34',
    messagingSenderId: '138177769693',
    projectId: 'real-escrm-ia',
    storageBucket: 'real-escrm-ia.firebasestorage.app',
    iosBundleId: 'com.example.realEstateCrm',
  );
}
